pipeline:
  build:
    image: julia:${JULIA_VERSION}
    commands:
      - echo ${JULIA_VERSION}
      - mkdir -p /root/.julia/v${JULIA_VERSION}/
      - cp -r /drone/src /root/.julia/v${JULIA_VERSION}/StructTables/
      - which diff
      - julia -e 'Pkg.resolve(); Pkg.build("StructTables"); Pkg.test("StructTables"; coverage=true)'

matrix:
  JULIA_VERSION:
    - 0.5
